### ISSUE TITLE
Integrate cli package into demo

### ISSUE THREAD

**Issue by kittybest** [privacy-scaling-explorations/maci-rpgf#1]
### Description

As a user I'd like to use `maci-cli` package for my frontend app.

### Acceptance criteria

- [ ] Implement user dashboard
- [ ] Support user signups
- [ ] Support user message publish
- [ ] Support user keypair change
- [ ] Implement coordinator dashboard
- [ ] Support coordinator tree merging
- [ ] Support coordinator poll finalization
- [ ] Support displaying all the information related to poll (subgraph and ethers)

**Comment by samajammin** [comment]
Closing in favor of https://github.com/privacy-scaling-explorations/maci/issues/1097
