### ISSUE TITLE
UX: Increase the clickable area when uploading project background 

### ISSUE THREAD

**Issue by aguzmant103** [privacy-scaling-explorations/maci-rpgf#105]
Report from user from Loom: https://www.loom.com/share/7da7aae4aa9e4a9cb48965e73e61f1a6?sid=ef95c42e-f387-48c2-84d6-4a0d68334082

**Comment by KcPele** [comment]
Gm gm, i can't find the documentation for contributing and would love to contribute

**Comment by ctrlc03** [comment]
> Gm gm, i can't find the documentation for contributing and would love to contribute

thanks very much for fixing this and for wanting to contribute to this project🫡
