### ISSUE TITLE
Bug: Hide Sign up if already signed up

### ISSUE THREAD

**Issue by aguzmant103** [privacy-scaling-explorations/maci-rpgf#108]
Report from user from Loom: https://www.loom.com/share/7da7aae4aa9e4a9cb48965e73e61f1a6?sid=ef95c42e-f387-48c2-84d6-4a0d68334082

**Comment by ctrlc03** [comment]
Seems like this is already fixed? @kittybest @crisgarner can you confirm please?

**Comment by ctrlc03** [comment]
so the issue here it's that the check if a user is signed up fails because it tries to fetch more than 1024 block at a time, so it will just throw. We need to fix this on MACI side https://github.com/privacy-scaling-explorations/maci/blob/dev/cli/ts/commands/signup.ts#L106

**Comment by ctrlc03** [comment]
fixed by #138
