### ISSUE TITLE
Not able to create an application if information is pending

### ISSUE THREAD

**Issue by crisgarner** [privacy-scaling-explorations/maci-rpgf#128]
When creating an application, if contributions links or impact metrics are removed, it doesn't allow an application to be created and no error is shown.

Steps to reproduce:

1. Create an Application
2. Remove Contribution Links, Metrics
3. Try to create an application

**Comment by crisgarner** [comment]
Seems like Funding sources aren't required and have no issues

**Comment by kittybest** [comment]
close by #222
