### ISSUE TITLE
New version v1.2.3 doesn't allow to vote

### ISSUE THREAD

**Issue by crisgarner** [privacy-scaling-explorations/maci-rpgf#148]
The new version sets the votes to 0 and doesn't allow to vote.

![image](https://github.com/privacy-scaling-explorations/maci-rpgf/assets/578688/5b5ef278-3fc7-463b-9d30-7887fe1052ec)

This screenshot was taken using the same contracts as the previous screenshot

![Screenshot 2024-05-31 at 4 15 47 PM](https://github.com/privacy-scaling-explorations/maci-rpgf/assets/578688/a967187c-6bfc-4922-9ecb-b691c3fb18ad)

**Comment by ctrlc03** [comment]
I'm closing this in favour of #153 to prevent any confusion and clearly focus on the issue
