### ISSUE TITLE
Bug(frontend): refreshing problem

### ISSUE THREAD

**Issue by kittybest** [privacy-scaling-explorations/maci-rpgf#183]
based on the conversation here: https://github.com/privacy-scaling-explorations/maci-rpgf/pull/179#discussion_r1655628187

This is not only a problem in `feat/design-ui` but also a problem of `main`, should make a PR for this bug.

**Comment by ctrlc03** [comment]
fixed by #186 right?

**Comment by kittybest** [comment]
> fixed by #186 right?

yes
