### ISSUE TITLE
Create package for RPGF demo within MACI repo

### ISSUE THREAD

**Issue by kittybest** [privacy-scaling-explorations/maci-rpgf#2]
### Description

As part of this we should probably create/select a web app (decide which project to fork or to start from scratch), given that if we fork a project, that could be the same step of creating the repo

### Acceptance criteria

- [ ] Decide which frontend app to use for demo (https://github.com/gitcoinco/easy-retro-pgf)
- [ ] Add fork https://github.com/gitcoinco/easy-retro-pgf
- [ ] Support all the dev checks: build, lint, types and etc.

**Comment by samajammin** [comment]
Closing in favor of https://github.com/privacy-scaling-explorations/maci/issues/1099
