### ISSUE TITLE
Bug(Frontend): clicking projects on navbar will load nothing

### ISSUE THREAD

**Issue by kittybest** [privacy-scaling-explorations/maci-rpgf#22]
`useFilter` would check the queries and pass them to the `project.search` function.
https://github.com/privacy-scaling-explorations/maci-rpgf/blob/04b5a592f56a9621bdc4fee8182fca66d5c34dc0/src/features/projects/hooks/useProjects.ts#L23

Q1: why click on **projects** on the navbar automatically add these queries? ➡️ these might be the initial queries, was set because of the function `setFilters`
Q2: why we already set `type Filter.seed` to `number` here
https://github.com/privacy-scaling-explorations/maci-rpgf/blob/04b5a592f56a9621bdc4fee8182fca66d5c34dc0/src/features/filter/types/index.ts#L11
but it's still a `string` instead of a `number`?
The above `FilterSchema` is checking the type while calling `project.search` api, so we still need to make sure we pass correct type of queries to server.
https://github.com/privacy-scaling-explorations/maci-rpgf/blob/04b5a592f56a9621bdc4fee8182fca66d5c34dc0/src/features/filter/hooks/useFilter.ts#L64
`toURL` set everything to string.

**Comment by samajammin** [comment]
Fixed in #26

(@kittybest if I'm mistaken, please re-open)
