### ISSUE TITLE
Feat(frontend): user dashboard UI

### ISSUE THREAD

**Issue by kittybest** [privacy-scaling-explorations/maci-rpgf#3]
should contain:
- [ ] my ballot details
- [ ] edit my ballot
- [ ] submit my ballot to vote (related issue #7 )
- [ ] change my key (related issue #7 )
- [ ] check my ballot submit

**might be problem**
should we design it?

**Comment by samajammin** [comment]
This _should_ largely be solved by the existing EasyRetroPGF app... will have to see what we need to update/change

**Comment by samajammin** [comment]
> change my key (which is message type 2 for vote --> related issue https://github.com/privacy-scaling-explorations/maci-rpgf/issues/7 )

I'd argue we don't even need to solve for key switching as part of this demo

**Comment by samajammin** [comment]
Closing out for now, I think EasyRetroPGF app already has these UI flows 🎉
