### ISSUE TITLE
Create homepage

### ISSUE THREAD

**Issue by samajammin** [privacy-scaling-explorations/maci-rpgf#55]
As a user, if I've never used an RPGF interface, it's unclear what the flow of this application is

More detailed feedback in this video:
https://www.loom.com/share/21b2812f704b4ad39248ce441bfce813?sid=7f9f0ea5-bba7-44be-87c7-5178bae08cc4

Let's create a homepage that explains
- What is RPGF
- How it works
- What a user needs to participate (ETH for gas, EAS attestation to vote, [link to projects page](https://maci-rpgf.vercel.app/projects)) 
- What a project needs to participate (how to apply, [link to application page](https://maci-rpgf.vercel.app/applications/new))

**Comment by kittybest** [comment]
Beside contents mentioned above, 
- display current stage (Submit application / register as a voter / voting start / voting end / tally result)
- beside the description of "what is RPGF" and "how it works", the main part of the page display different content according to current stage
- but user could still switch the main content to display passed or future stages
- detailed description about how the current stage works

What need to be more discussed:
- do we still need to collect the voters' addresses through `/voters`  page? (process: users apply to become voters ➡️ coordinator approve or reject it by giving the address an attestation on approval schema or not ➡️ users find themselves be able to signup ➡️ they click signup to register to maci contract)

**Comment by samajammin** [comment]
@kittybest I think as a starting point we could grab the code from this fork: https://github.com/gitcoinco/easy-retro-pgf-filecoin/

Simple homepage but has a nice round progress component: https://github.com/gitcoinco/easy-retro-pgf-filecoin/blob/main/src/features/info/components/RoundProgress.tsx

**Comment by aguzmant103** [comment]
Designs are close to ready at https://www.figma.com/design/2ADLprS4xgd0n3seuScE8V/%F0%9F%97%B3%EF%B8%8F-MACI-RPGF?node-id=60-1014&t=UF2oz7fflbyHib98-4

**Comment by kittybest** [comment]
close this by #137 , also change to another new issue for a multi-round homepage.
