### ISSUE TITLE
Deploy coordinator service

### ISSUE THREAD

**Issue by 0xmad** [privacy-scaling-explorations/maci-rpgf#58]
- [ ] Deploy coordinator service so it's accessible from maci-rpgf app

**Comment by kittybest** [comment]
Also need to:
- confirm PSE Amazon account
- Sam mentioned a PSE-built RPC endpoints: https://www.notion.so/pse-team/Set-up-RPC-service-32c45a45c9464d058fdd8a43a5ccdab7?pvs=4
