### ISSUE TITLE
Feat(contracts): EASSignupGateKeeper

### ISSUE THREAD

**Issue by kittybest** [privacy-scaling-explorations/maci-rpgf#6]
we should implement our own gate keeper by passing EAS data inside and prove it. (or passing address to it?)

**【UPDATE】**
https://github.com/privacy-scaling-explorations/maci/pull/1109
related to above PR.

**Comment by samajammin** [comment]
Closing this out - covered in https://github.com/privacy-scaling-explorations/maci/pull/1109
