### ISSUE TITLE
Deal with several bugs and improvements

### ISSUE THREAD

**Issue by kittybest** [privacy-scaling-explorations/maci-rpgf#68]
Bugs and improvements suggested by Vee here: https://www.notion.so/pse-team/RPGF-feedback-1476b27526574f8aa8ae677988b7f135

- [x] Make sure there are not redundant messages being shown on the page
- [x] Make sure the `sign up` process is fluent enough under most of the conditions
- [x] Make sure the state is consistent across pages
- [x] Allow user to modify the community's name (default `optimism` everywhere now)
- [x] Other adjustment suggestions on UI message display

**Comment by ctrlc03** [comment]
@kittybest think these are done now in `feat/design-ui`?

**Comment by kittybest** [comment]
> @kittybest think these are done now in `feat/design-ui`?

I think so :)
