### ISSUE TITLE
Poll querying/loading state issues

### ISSUE THREAD

**Issue by samajammin** [privacy-scaling-explorations/maci-rpgf#69]
Not a great UX when loading the /projects page:

https://github.com/privacy-scaling-explorations/maci-rpgf/assets/8097623/29264851-6e57-4ee3-a84a-ac23578c65b3

Initially displays "voting has ending" before updating to show the time left. Not sure if this is an issue with our loading/pending states, but we should have a loading UI & copy that makes it clear we're fetching the up-to-date information. We shouldn't risk displaying information that's incorrect.

- [ ] Confirm this is an issue with fetching data from the contract
- [ ] If so, let's add a pending state to say "fetching round data" until we have the info about the round from the contract

**Comment by ctrlc03** [comment]
was this fixed by #88? @kittybest

**Comment by kittybest** [comment]
> was this fixed by #88? @kittybest

yes, close this issue :)
