### ISSUE TITLE
Bug: fetch attestation with correct attesterId

### ISSUE THREAD

**Issue by kittybest** [privacy-scaling-explorations/maci-rpgf#87]
![image](https://github.com/privacy-scaling-explorations/maci-rpgf/assets/9023842/676806de-07fc-4ba3-a159-fcc6ee3f8525)

The problem is: `AttesterNotTrusted()`

Which is originated from here: https://github.com/privacy-scaling-explorations/maci-rpgf/blob/d3594cb907e2486c7625a53e45e5a28bc6ad63bd/src/contexts/Maci.tsx#L57

Should modify this line to match the attesterId.

**Comment by ctrlc03** [comment]
did #90 fix this? @kittybest

**Comment by kittybest** [comment]
> did #90 fix this? @kittybest

kind of? but since sometimes I will put multiple addresses as admins, but the EASGatekeeper only accept one valid attester, so I opened another PR for this: https://github.com/privacy-scaling-explorations/maci-rpgf/pull/122

And it seems like already merged, so I would close this issue.
