### ISSUE TITLE
Improvements and Bugs on Create Applications page 

### ISSUE THREAD

**Issue by crisgarner** [privacy-scaling-explorations/maci-rpgf#92]
- [x]  The error message is not clear, and the instructions for currency are not clear.
- [x]  Impact categories are specific to Optimism, this should be configurable.
- [x] Add a question for contact applicants (contact not personal information)

Screenshots are visible on: https://www.notion.so/pse-team/RPGF-feedback-1476b27526574f8aa8ae677988b7f135

**Comment by kittybest** [comment]
@crisgarner do you think we should let the user to add their contact information on the application page? should it be telegram? email address? or something else? This should be added to the design v2.0.

**Comment by crisgarner** [comment]
There is value in organizers contacting applicants (like requesting more details or in case they forget to claim the funds), which happens a lot, but applicants need to understand that this is public information. If we are thinking about v2.0 I think giving the flexibility to round runners to create their custom forms would be a nice feature, (maybe using a .md or json file). So far all communities had different needs regarding questions to ask for projects.

**Comment by kittybest** [comment]
close by #194 #222
