### ISSUE TITLE
Wallet Session is not well-preserved.

### ISSUE THREAD

**Issue by crisgarner** [privacy-scaling-explorations/maci-rpgf#95]
If the admin connects and signs out, it keeps showing the menu state as if it was an admin even disconnected.

![image](https://github.com/privacy-scaling-explorations/maci-rpgf/assets/578688/a8c9bcfd-1a93-446d-adc0-c2b3f5b5156f)

**Comment by ctrlc03** [comment]
> If the admin connects and signs out, it keeps showing the menu state as if it was an admin even disconnected.
> 
> ![image](https://private-user-images.githubusercontent.com/578688/329409658-a8c9bcfd-1a93-446d-adc0-c2b3f5b5156f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMzU1NjQsIm5iZiI6MTcxNTMzNTI2NCwicGF0aCI6Ii81Nzg2ODgvMzI5NDA5NjU4LWE4YzliY2ZkLTFhOTMtNDQ2ZC1hZGMwLWMyYjNmNWI1MTU2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQxMDAxMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OTYwYjBiOWVjMDc0Yjk4YmFkYWZiZTBiYmM1NzJkNTA4NmEzMzA4YzU0NjBhNTEyMzFkNzMwYmQwMjdkNTBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7rguFG6ileA1WsDOEGKpDTKw50jhHmQYUSl6mr4hC-g)

I don't get that, when I disconnect it disappears straight away 🤔

**Comment by ctrlc03** [comment]
But if I'm on one of those pages, it doesn't redirect me to the home page

**Comment by crisgarner** [comment]
I'll work on fixing the permission then, it's a weird bug wasn't able to replicate again, I know ETH TGU dev had the same issue.
