### ISSUE TITLE
Improvements and bugs

### ISSUE THREAD

**Issue by crisgarner** [privacy-scaling-explorations/maci-rpgf#96]
- [x] After Sign Up, clicking on the View Ballot button allows us to see an empty ballot before the rounds start.
- [x] There are multiple mentions and links related to “Lists”, MACI RPGF doesn’t support lists so we should remove them.
- [x] Project approvals, and adding voters, should be instant not 10 minutes.
- [x] Project applications are bugged, take a lot of time, and sometimes appear as approved then a few seconds disappears. 
- [x] As a voter, am I supposed to see the “Import CSV”, “Export CSV” and “View lists” functions?
![image](https://github.com/privacy-scaling-explorations/maci-rpgf/assets/578688/f332199b-a8c2-421e-ad3d-4e2c1ef0bf47)
- [x] As a voter, being asked to connect my wallet, then sign up by connecting my wallet again to view my ballot, and then to sign a message via my wallet - these 3 transactions seem to fall under the same mental category of needing to connect to my wallet and thus feel repetitive. If there is no way we can make this into a 1 or 2-step process, then we could explain why a voter would have to go through these 3 steps.

**Comment by crisgarner** [comment]
Another solution is changing the name of the sign up button.

**Comment by kittybest** [comment]
remove import csv / export csv by PR #157

**Comment by ctrlc03** [comment]
@crisgarner I believe the 10 minutes message is just a warning in case that EAS's graph is not updated straight away, so probably we can just change the copy to inform of that (cc @kittybest )

**Comment by crisgarner** [comment]
Also just to note, some of these issues are being solved on the new design

**Comment by kittybest** [comment]
close by #218 and #137
