### ISSUE TITLE
Duplicated banner in projects 

### ISSUE THREAD

**Issue by crisgarner** [privacy-scaling-explorations/maci-rpgf#97]
When creating multiple applications using a single wallet, the banner from the first project is duplicated across the other projects

![image](https://github.com/privacy-scaling-explorations/maci-rpgf/assets/578688/9512c41b-39f0-4d6e-b11f-aeb789a56b28)

**Comment by crisgarner** [comment]
This error happens also in the Review Applications 
![image](https://github.com/privacy-scaling-explorations/maci-rpgf/assets/578688/9eadc44e-a308-4fac-98f8-04a1cd066f21)

**Comment by crisgarner** [comment]
Most likely this issue is because the applications are being searched by the recipient, this issue can be solved by not having two recipients with the same address, or changing the query to look for id. In theory, we wouldn't want to have projects applying with the same recipient.

**Comment by kittybest** [comment]
fixed by removing the `profileSchema` in PR #194
